// flexible-graphrag-ui/frontend-react/src/components/SourcesTab.tsx
import React, { useState, useCallback } from 'react';
import {
  Box,
  Typography,
  Button,
  FormControl,
  InputLabel,
  Select,
  MenuItem,
} from '@mui/material';
import { Theme } from '@mui/material/styles';
import {
  FileUploadForm,
  AlfrescoSourceForm,
  NuxeoSourceForm,
  CMISSourceForm,
  WebSourceForm,
  WikipediaSourceForm,
  YouTubeSourceForm,
  S3SourceForm,
  GCSSourceForm,
  AzureBlobSourceForm,
  OneDriveSourceForm,
  SharePointSourceForm,
  BoxSourceForm,
  GoogleDriveSourceForm,
} from './sources';

interface SourcesTabProps {
  currentTheme: Theme;
  dataSource: string;
  selectedFiles: File[];
  folderPath: string;
  cmisUrl: string;
  cmisUsername: string;
  cmisPassword: string;
  nuxeoFormValue: any;
  onNuxeoFormChange: (config: any) => void;
  alfrescoFormValue: any;
  onAlfrescoFormChange: (config: any) => void;
  // Web sources
  webUrl: string;
  wikipediaUrl: string;
  youtubeUrl: string;
  // Cloud storage
  s3AccessKey: string;
  s3SecretKey: string;
  gcsBucketName: string;
  gcsCredentials: string;
  azureBlobConnectionString: string;
  azureBlobContainer: string;
  azureBlobName: string;
  azureBlobAccountName: string;
  azureBlobAccountKey: string;
  // Enterprise
  onedriveUserPrincipalName: string;
  onedriveClientId: string;
  onedriveClientSecret: string;
  onedriveTenantId: string;
  sharepointSiteName: string;  // Changed from sharepointSiteUrl to sharepointSiteName
  boxClientId: string;
  boxClientSecret: string;
  boxDeveloperToken: string;
  boxUserId: string;
  boxEnterpriseId: string;
  googleDriveCredentials: string;
  onDataSourceChange: (dataSource: string) => void;
  onSelectedFilesChange: (files: File[]) => void;
  onFolderPathChange: (folderPath: string) => void;
  onCmisUrlChange: (url: string) => void;
  onCmisUsernameChange: (username: string) => void;
  onCmisPasswordChange: (password: string) => void;
  // Web sources handlers
  onWebUrlChange: (url: string) => void;
  onWikipediaUrlChange: (url: string) => void;
  onYoutubeUrlChange: (url: string) => void;
  // Cloud storage handlers
  onS3AccessKeyChange: (key: string) => void;
  onS3SecretKeyChange: (key: string) => void;
  onGcsBucketNameChange: (name: string) => void;
  onGcsCredentialsChange: (creds: string) => void;
  onAzureBlobConnectionStringChange: (conn: string) => void;
  onAzureBlobContainerChange: (container: string) => void;
  onAzureBlobNameChange: (name: string) => void;
  onAzureBlobAccountNameChange: (accountName: string) => void;
  onAzureBlobAccountKeyChange: (accountKey: string) => void;
  // Enterprise handlers
  onOnedriveUserPrincipalNameChange: (name: string) => void;
  onOnedriveClientIdChange: (id: string) => void;
  onOnedriveClientSecretChange: (secret: string) => void;
  onOnedriveTenantIdChange: (id: string) => void;
  onSharepointSiteNameChange: (name: string) => void;  // Changed from onSharepointSiteUrlChange
  onBoxClientIdChange: (id: string) => void;
  onBoxClientSecretChange: (secret: string) => void;
  onBoxDeveloperTokenChange: (token: string) => void;
  onBoxUserIdChange: (userId: string) => void;
  onBoxEnterpriseIdChange: (enterpriseId: string) => void;
  onGoogleDriveCredentialsChange: (creds: string) => void;
  onConfigureProcessing: () => void;
  onSourcesConfigured: (data: {
    dataSource: string;
    files: File[];
    folderPath: string;
    cmisConfig?: any;
    alfrescoConfig?: any;
    nuxeoConfig?: any;
    webConfig?: any;
    cloudConfig?: any;
    enterpriseConfig?: any;
  }) => void;
}

export const SourcesTab: React.FC<SourcesTabProps> = ({ 
  currentTheme,
  dataSource,
  selectedFiles,
  folderPath,
  cmisUrl,
  cmisUsername,
  cmisPassword,
  nuxeoFormValue,
  onNuxeoFormChange,
  alfrescoFormValue,
  onAlfrescoFormChange,
  // Web sources
  webUrl,
  wikipediaUrl,
  youtubeUrl,
  // Cloud storage
  s3AccessKey,
  s3SecretKey,
  gcsBucketName,
  gcsCredentials,
  azureBlobConnectionString,
  azureBlobContainer,
  azureBlobName,
  azureBlobAccountName,
  azureBlobAccountKey,
  // Enterprise
  onedriveUserPrincipalName,
  onedriveClientId,
  onedriveClientSecret,
  onedriveTenantId,
  sharepointSiteName,  // Changed from sharepointSiteUrl
  boxClientId,
  boxClientSecret,
  boxDeveloperToken,
  boxUserId,
  boxEnterpriseId,
  googleDriveCredentials,
  onDataSourceChange,
  onSelectedFilesChange,
  onFolderPathChange,
  onCmisUrlChange,
  onCmisUsernameChange,
  onCmisPasswordChange,
  // Web sources handlers
  onWebUrlChange,
  onWikipediaUrlChange,
  onYoutubeUrlChange,
  // Cloud storage handlers
  onS3AccessKeyChange,
  onS3SecretKeyChange,
  onGcsBucketNameChange,
  onGcsProjectIdChange,
  onGcsCredentialsChange,
  onAzureBlobConnectionStringChange,
  onAzureBlobContainerChange,
  onAzureBlobNameChange,
  onAzureBlobAccountNameChange,
  onAzureBlobAccountKeyChange,
  // Enterprise handlers
  onOnedriveUserPrincipalNameChange,
  onOnedriveClientIdChange,
  onOnedriveClientSecretChange,
  onOnedriveTenantIdChange,
  onSharepointSiteNameChange,  // Changed from onSharepointSiteUrlChange
  onBoxClientIdChange,
  onBoxClientSecretChange,
  onBoxDeveloperTokenChange,
  onBoxUserIdChange,
  onBoxEnterpriseIdChange,
  onGoogleDriveCredentialsChange,
  onConfigureProcessing, 
  onSourcesConfigured 
}) => {
  // Local state for form validation and configuration
  const [isFormValid, setIsFormValid] = useState<boolean>(false);
  const [currentConfig, setCurrentConfig] = useState<any>(null);

  // Handlers for modular components
  const handleValidationChange = useCallback((isValid: boolean) => {
    setIsFormValid(isValid);
  }, []);

  const handleConfigurationChange = useCallback((config: any) => {
    console.log('Configuration changed:', dataSource, config);
    setCurrentConfig(config);
  }, [dataSource]);


  const handleConfigureProcessing = () => {
    // Build configuration data based on current source and config
    console.log('Configure processing - dataSource:', dataSource, 'currentConfig:', currentConfig);
    const configData = {
      dataSource,
      files: dataSource === 'upload' ? selectedFiles : [],
      folderPath: dataSource === 'cmis'
        ? folderPath
        : ((dataSource === 'alfresco' || dataSource === 'nuxeo') ? (currentConfig?.path || '') : ''),
      // Legacy configs for backward compatibility
      cmisConfig: dataSource === 'cmis' ? currentConfig : undefined,
      alfrescoConfig: dataSource === 'alfresco' ? currentConfig : undefined,
      nuxeoConfig: dataSource === 'nuxeo' ? currentConfig : undefined,
      // New modular configs  
      webConfig: dataSource === 'web' ? currentConfig : undefined,
      wikipediaConfig: dataSource === 'wikipedia' ? currentConfig : undefined,
      youtubeConfig: dataSource === 'youtube' ? currentConfig : undefined,
      cloudConfig: ['s3', 'gcs', 'azure_blob'].includes(dataSource) ? {
        type: dataSource,
        ...currentConfig
      } : undefined,
      enterpriseConfig: ['onedrive', 'sharepoint', 'box', 'google_drive'].includes(dataSource) ? {
        type: dataSource,
        ...currentConfig
      } : undefined
    };
    
    onSourcesConfigured(configData);
    onConfigureProcessing();
  };

  const renderDataSourceFields = () => {
    switch (dataSource) {
      case 'upload':
        return (
          <FileUploadForm
            currentTheme={currentTheme}
            selectedFiles={selectedFiles}
            onSelectedFilesChange={onSelectedFilesChange}
            onConfigurationChange={handleConfigurationChange}
            onValidationChange={handleValidationChange}
          />
        );
      
      case 'cmis':
        return (
          <CMISSourceForm
            currentTheme={currentTheme}
            url={cmisUrl}
            username={cmisUsername}
            password={cmisPassword}
            folderPath={folderPath}
            onUrlChange={onCmisUrlChange}
            onUsernameChange={onCmisUsernameChange}
            onPasswordChange={onCmisPasswordChange}
            onFolderPathChange={onFolderPathChange}
            onConfigurationChange={handleConfigurationChange}
            onValidationChange={handleValidationChange}
          />
        );
      
      case 'alfresco':
        return (
          <AlfrescoSourceForm
            currentTheme={currentTheme}
            value={alfrescoFormValue}
            onChange={onAlfrescoFormChange}
            onConfigurationChange={handleConfigurationChange}
            onValidationChange={handleValidationChange}
          />
        );
      
      case 'nuxeo':
        return (
          <NuxeoSourceForm
            currentTheme={currentTheme}
            value={nuxeoFormValue}
            onChange={onNuxeoFormChange}
            onConfigurationChange={handleConfigurationChange}
            onValidationChange={handleValidationChange}
          />
        );

      case 'web':
        return (
          <WebSourceForm
            currentTheme={currentTheme}
            url={webUrl}
            onUrlChange={onWebUrlChange}
            onConfigurationChange={handleConfigurationChange}
            onValidationChange={handleValidationChange}
          />
        );
      
      case 'wikipedia':
        return (
          <WikipediaSourceForm
            currentTheme={currentTheme}
            url={wikipediaUrl}
            onUrlChange={onWikipediaUrlChange}
            onConfigurationChange={handleConfigurationChange}
            onValidationChange={handleValidationChange}
          />
        );
      
      case 'youtube':
        return (
          <YouTubeSourceForm
            currentTheme={currentTheme}
            url={youtubeUrl}
            onUrlChange={onYoutubeUrlChange}
            onConfigurationChange={handleConfigurationChange}
            onValidationChange={handleValidationChange}
          />
        );
      
      case 's3':
        return (
          <S3SourceForm
            currentTheme={currentTheme}
            accessKey={s3AccessKey}
            secretKey={s3SecretKey}
            onAccessKeyChange={onS3AccessKeyChange}
            onSecretKeyChange={onS3SecretKeyChange}
            onConfigurationChange={handleConfigurationChange}
            onValidationChange={handleValidationChange}
          />
        );
      
      case 'gcs':
        return (
          <GCSSourceForm
            currentTheme={currentTheme}
            bucketName={gcsBucketName}
            credentials={gcsCredentials}
            onBucketNameChange={onGcsBucketNameChange}
            onCredentialsChange={onGcsCredentialsChange}
            onConfigurationChange={handleConfigurationChange}
            onValidationChange={handleValidationChange}
          />
        );
      
      case 'azure_blob':
        return (
          <AzureBlobSourceForm
            currentTheme={currentTheme}
            connectionString={azureBlobConnectionString}
            containerName={azureBlobContainer}
            blobName={azureBlobName}
            accountName={azureBlobAccountName}
            accountKey={azureBlobAccountKey}
            onConnectionStringChange={onAzureBlobConnectionStringChange}
            onContainerNameChange={onAzureBlobContainerChange}
            onBlobNameChange={onAzureBlobNameChange}
            onAccountNameChange={onAzureBlobAccountNameChange}
            onAccountKeyChange={onAzureBlobAccountKeyChange}
            onConfigurationChange={handleConfigurationChange}
            onValidationChange={handleValidationChange}
          />
        );
      
      case 'onedrive':
        return (
          <OneDriveSourceForm
            currentTheme={currentTheme}
            userPrincipalName={onedriveUserPrincipalName}
            clientId={onedriveClientId}
            clientSecret={onedriveClientSecret}
            tenantId={onedriveTenantId}
            onUserPrincipalNameChange={onOnedriveUserPrincipalNameChange}
            onClientIdChange={onOnedriveClientIdChange}
            onClientSecretChange={onOnedriveClientSecretChange}
            onTenantIdChange={onOnedriveTenantIdChange}
            onConfigurationChange={handleConfigurationChange}
            onValidationChange={handleValidationChange}
          />
        );
      
      case 'sharepoint':
        return (
          <SharePointSourceForm
            currentTheme={currentTheme}
            siteName={sharepointSiteName}  // Changed from siteUrl to siteName
            clientId={onedriveClientId}
            clientSecret={onedriveClientSecret}
            tenantId={onedriveTenantId}
            onSiteNameChange={onSharepointSiteNameChange}  // Changed from onSiteUrlChange
            onClientIdChange={onOnedriveClientIdChange}
            onClientSecretChange={onOnedriveClientSecretChange}
            onTenantIdChange={onOnedriveTenantIdChange}
            onConfigurationChange={handleConfigurationChange}
            onValidationChange={handleValidationChange}
          />
        );
      
      case 'box':
        return (
          <BoxSourceForm
            currentTheme={currentTheme}
            clientId={boxClientId}
            clientSecret={boxClientSecret}
            developerToken={boxDeveloperToken}
            userId={boxUserId}
            enterpriseId={boxEnterpriseId}
            onClientIdChange={onBoxClientIdChange}
            onClientSecretChange={onBoxClientSecretChange}
            onDeveloperTokenChange={onBoxDeveloperTokenChange}
            onUserIdChange={onBoxUserIdChange}
            onEnterpriseIdChange={onBoxEnterpriseIdChange}
            onConfigurationChange={handleConfigurationChange}
            onValidationChange={handleValidationChange}
          />
        );
      
      case 'google_drive':
        return (
          <GoogleDriveSourceForm
            currentTheme={currentTheme}
            credentials={googleDriveCredentials}
            onCredentialsChange={onGoogleDriveCredentialsChange}
            onConfigurationChange={handleConfigurationChange}
            onValidationChange={handleValidationChange}
          />
        );
      
      default:
        return null;
    }
  };

  return (
    <Box sx={{ p: 3 }}>
      <Typography variant="h6" gutterBottom>
        Data Source Configuration
      </Typography>
      
      <FormControl sx={{ mb: 2, maxWidth: 400, width: '100%' }}>
        <InputLabel>Data Source</InputLabel>
        <Select
          value={dataSource}
          label="Data Source"
          onChange={(e) => onDataSourceChange(e.target.value)}
          size="small"
        >
          <MenuItem value="upload">File Upload</MenuItem>
          <MenuItem value="alfresco">Alfresco Repository</MenuItem>
          <MenuItem value="nuxeo">Nuxeo Repository</MenuItem>
          <MenuItem value="cmis">CMIS Repository</MenuItem>
          <MenuItem disabled>─── Web ───</MenuItem>
          <MenuItem value="web">Web Page</MenuItem>
          <MenuItem value="wikipedia">Wikipedia</MenuItem>
          <MenuItem value="youtube">YouTube</MenuItem>
          <MenuItem disabled>─── Cloud ───</MenuItem>
          <MenuItem value="google_drive">Google Drive</MenuItem>
          <MenuItem value="onedrive">Microsoft OneDrive</MenuItem>
          <MenuItem value="s3">Amazon S3</MenuItem>
          <MenuItem value="azure_blob">Azure Blob Storage</MenuItem>
          <MenuItem value="gcs">Google Cloud Storage</MenuItem>
          <MenuItem disabled>─── Enterprise ───</MenuItem>
          <MenuItem value="box">Box</MenuItem>
          <MenuItem value="sharepoint">SharePoint</MenuItem>
        </Select>
      </FormControl>
      
      {renderDataSourceFields()}
      
      <Box sx={{ display: 'flex', gap: 1, alignItems: 'center', mt: 2 }}>
        <Button
          variant="contained"
          onClick={handleConfigureProcessing}
          disabled={!isFormValid}
          sx={{ minWidth: 200 }}
        >
          Configure Processing →
        </Button>
      </Box>
    </Box>
  );
};

// flexible-graphrag-ui/frontend-vue/src/components/SourcesTab.vue
<template>
  <div class="pa-4">
    <h2 class="mb-4">Data Source Configuration</h2>
    
    <!-- Data Source Selection -->
    <v-select
      v-model="dataSource"
      :items="dataSourceOptions"
      label="Data Source"
      variant="outlined"
      class="mb-4 data-source-select"
      :menu-props="{
        maxHeight: 'none',
        maxWidth: 400
      }"
      density="compact"
    ></v-select>

    <!-- Dynamic Source Forms -->
    <component
      :is="currentSourceComponent"
      v-if="currentSourceComponent"
      v-bind="currentSourceProps"
      @configuration-change="handleConfigurationChange"
      @validation-change="handleValidationChange"
    />

    <!-- Configure Processing Button -->
    <div class="d-flex align-center mt-4">
      <v-btn
        color="primary"
        size="large"
        :disabled="!isFormValid"
        @click="configureProcessing"
      >
        CONFIGURE PROCESSING →
      </v-btn>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref, computed, watch } from 'vue';
import axios from 'axios';
import {
  FileUploadForm,
  AlfrescoSourceForm,
  NuxeoSourceForm,
  CMISSourceForm,
  WebSourceForm,
  WikipediaSourceForm,
  YouTubeSourceForm,
  S3SourceForm,
  GCSSourceForm,
  AzureBlobSourceForm,
  OneDriveSourceForm,
  SharePointSourceForm,
  BoxSourceForm,
  GoogleDriveSourceForm,
} from './sources';

export default defineComponent({
  name: 'SourcesTab',
  props: {
    // Single-object form state held in App (persists across tab switches).
    nuxeoFormValue: { type: Object, default: () => ({}) },
    alfrescoFormValue: { type: Object, default: () => ({}) },
  },
  emits: ['configure-processing', 'sources-configured', 'update:nuxeoFormValue', 'update:alfrescoFormValue'],
  setup(props, { emit }) {
    // Data source options - matching React order exactly
    const dataSourceOptions = [
      { title: 'File Upload', value: 'upload' },
      { title: 'Alfresco Repository', value: 'alfresco' },
      { title: 'Nuxeo Repository', value: 'nuxeo' },
      { title: 'CMIS Repository', value: 'cmis' },
      { title: '─── Web ───', value: '', disabled: true },
      { title: 'Web Page', value: 'web' },
      { title: 'Wikipedia', value: 'wikipedia' },
      { title: 'YouTube', value: 'youtube' },
      { title: '─── Cloud ───', value: '', disabled: true },
      { title: 'Google Drive', value: 'google_drive' },
      { title: 'Microsoft OneDrive', value: 'onedrive' },
      { title: 'Amazon S3', value: 's3' },
      { title: 'Azure Blob Storage', value: 'azure_blob' },
      { title: 'Google Cloud Storage', value: 'gcs' },
      { title: '─── Enterprise ───', value: '', disabled: true },
      { title: 'Box', value: 'box' },
      { title: 'SharePoint', value: 'sharepoint' },
    ];

    // State
    const dataSource = ref('upload');
    const folderPath = ref('/Shared/GraphRAG');
    const selectedFiles = ref<File[]>([]);
    const isFormValid = ref(false);
    const currentConfig = ref<any>({});

    // CMIS state
    const cmisUrl = ref(`${import.meta.env.VITE_CMIS_BASE_URL || 'http://localhost:8080'}/alfresco/api/-default-/public/cmis/versions/1.1/atom`);
    const cmisUsername = ref('admin');
    const cmisPassword = ref('admin');

    // Web sources state
    const webUrl = ref('');
    const wikipediaUrl = ref('');
    const youtubeUrl = ref('');

    // Cloud storage state
    const s3AccessKey = ref('');
    const s3SecretKey = ref('');
    const gcsBucketName = ref('');
    const gcsCredentials = ref('');
    const azureBlobConnectionString = ref('');
    const azureBlobContainer = ref('');
    const azureBlobName = ref('');
    const azureBlobAccountName = ref('');
    const azureBlobAccountKey = ref('');

    // Enterprise state
    const onedriveUserPrincipalName = ref('');
    const onedriveClientId = ref('');
    const onedriveClientSecret = ref('');
    const onedriveTenantId = ref('');
    const sharepointSiteName = ref('');
    const sharepointClientId = ref('');
    const sharepointClientSecret = ref('');
    const sharepointTenantId = ref('');
    const boxClientId = ref('');
    const boxClientSecret = ref('');
    const boxDeveloperToken = ref('');
    const boxUserId = ref('');
    const boxEnterpriseId = ref('');
    const googleDriveCredentials = ref('');

    // Computed
    const currentSourceComponent = computed(() => {
      const componentMap: Record<string, any> = {
        upload: FileUploadForm,
        cmis: CMISSourceForm,
        alfresco: AlfrescoSourceForm,
        nuxeo: NuxeoSourceForm,
        web: WebSourceForm,
        wikipedia: WikipediaSourceForm,
        youtube: YouTubeSourceForm,
        s3: S3SourceForm,
        gcs: GCSSourceForm,
        azure_blob: AzureBlobSourceForm,
        onedrive: OneDriveSourceForm,
        sharepoint: SharePointSourceForm,
        box: BoxSourceForm,
        google_drive: GoogleDriveSourceForm,
      };
      return componentMap[dataSource.value] || null;
    });

    const currentSourceProps = computed(() => {
      const baseProps = {};
      
      switch (dataSource.value) {
        case 'upload':
          return {
            ...baseProps,
            selectedFiles: selectedFiles.value,
            'onUpdate:selectedFiles': (files: File[]) => { selectedFiles.value = files; }
          };
        case 'cmis':
          return {
            ...baseProps,
            url: cmisUrl.value,
            username: cmisUsername.value,
            password: cmisPassword.value,
            folderPath: folderPath.value,
            'onUpdate:url': (value: string) => { cmisUrl.value = value; },
            'onUpdate:username': (value: string) => { cmisUsername.value = value; },
            'onUpdate:password': (value: string) => { cmisPassword.value = value; },
            'onUpdate:folderPath': (value: string) => { folderPath.value = value; }
          };
        case 'nuxeo':
          return {
            ...baseProps,
            value: props.nuxeoFormValue,
            'onUpdate:value': (val: any) => { emit('update:nuxeoFormValue', val); },
          };
        case 'alfresco':
          return {
            ...baseProps,
            value: props.alfrescoFormValue,
            'onUpdate:value': (val: any) => { emit('update:alfrescoFormValue', val); },
          };
        case 'web':
          return {
            ...baseProps,
            url: webUrl.value,
            'onUpdate:url': (value: string) => { webUrl.value = value; }
          };
        case 'wikipedia':
          return {
            ...baseProps,
            url: wikipediaUrl.value,
            'onUpdate:url': (value: string) => { wikipediaUrl.value = value; }
          };
        case 'youtube':
          return {
            ...baseProps,
            url: youtubeUrl.value,
            'onUpdate:url': (value: string) => { youtubeUrl.value = value; }
          };
        case 's3':
          return {
            ...baseProps,
            accessKey: s3AccessKey.value,
            secretKey: s3SecretKey.value,
            'onUpdate:accessKey': (value: string) => { s3AccessKey.value = value; },
            'onUpdate:secretKey': (value: string) => { s3SecretKey.value = value; }
          };
        case 'gcs':
          return {
            ...baseProps,
            bucketName: gcsBucketName.value,
            credentials: gcsCredentials.value,
            'onUpdate:bucketName': (value: string) => { gcsBucketName.value = value; },
            'onUpdate:credentials': (value: string) => { gcsCredentials.value = value; }
          };
        case 'azure_blob':
          return {
            ...baseProps,
            connectionString: azureBlobConnectionString.value,
            containerName: azureBlobContainer.value,
            blobName: azureBlobName.value,
            accountName: azureBlobAccountName.value,
            accountKey: azureBlobAccountKey.value,
            'onUpdate:connectionString': (value: string) => { azureBlobConnectionString.value = value; },
            'onUpdate:containerName': (value: string) => { azureBlobContainer.value = value; },
            'onUpdate:blobName': (value: string) => { azureBlobName.value = value; },
            'onUpdate:accountName': (value: string) => { azureBlobAccountName.value = value; },
            'onUpdate:accountKey': (value: string) => { azureBlobAccountKey.value = value; }
          };
        case 'onedrive':
          return {
            ...baseProps,
            userPrincipalName: onedriveUserPrincipalName.value,
            clientId: onedriveClientId.value,
            clientSecret: onedriveClientSecret.value,
            tenantId: onedriveTenantId.value,
            'onUpdate:userPrincipalName': (value: string) => { onedriveUserPrincipalName.value = value; },
            'onUpdate:clientId': (value: string) => { onedriveClientId.value = value; },
            'onUpdate:clientSecret': (value: string) => { onedriveClientSecret.value = value; },
            'onUpdate:tenantId': (value: string) => { onedriveTenantId.value = value; }
          };
        case 'sharepoint':
          return {
            ...baseProps,
            siteName: sharepointSiteName.value,
            clientId: sharepointClientId.value,
            clientSecret: sharepointClientSecret.value,
            tenantId: sharepointTenantId.value,
            'onUpdate:siteName': (value: string) => { sharepointSiteName.value = value; },
            'onUpdate:clientId': (value: string) => { sharepointClientId.value = value; },
            'onUpdate:clientSecret': (value: string) => { sharepointClientSecret.value = value; },
            'onUpdate:tenantId': (value: string) => { sharepointTenantId.value = value; }
          };
        case 'box':
          return {
            ...baseProps,
            clientId: boxClientId.value,
            clientSecret: boxClientSecret.value,
            developerToken: boxDeveloperToken.value,
            userId: boxUserId.value,
            enterpriseId: boxEnterpriseId.value,
            'onUpdate:clientId': (value: string) => { boxClientId.value = value; },
            'onUpdate:clientSecret': (value: string) => { boxClientSecret.value = value; },
            'onUpdate:developerToken': (value: string) => { boxDeveloperToken.value = value; },
            'onUpdate:userId': (value: string) => { boxUserId.value = value; },
            'onUpdate:enterpriseId': (value: string) => { boxEnterpriseId.value = value; }
          };
        case 'google_drive':
          return {
            ...baseProps,
            credentials: googleDriveCredentials.value,
            'onUpdate:credentials': (value: string) => { googleDriveCredentials.value = value; }
          };
        default:
          return baseProps;
      }
    });

    // Methods
    const handleConfigurationChange = (config: any) => {
      currentConfig.value = config;
    };

    const handleValidationChange = (valid: boolean) => {
      isFormValid.value = valid;
    };

    const configureProcessing = () => {
      // Build configuration object based on data source
      const sourceConfig: any = {
        dataSource: dataSource.value,
        files: selectedFiles.value,
        folderPath: folderPath.value,
      };

      // Add source-specific configurations
      switch (dataSource.value) {
        case 'cmis':
          sourceConfig.cmisConfig = currentConfig.value;
          break;
        case 'alfresco':
          sourceConfig.alfrescoConfig = currentConfig.value;
          sourceConfig.folderPath = currentConfig.value?.path || '';
          break;
        case 'nuxeo':
          sourceConfig.nuxeoConfig = currentConfig.value;
          sourceConfig.folderPath = currentConfig.value?.path || '';
          break;
        case 'web':
          sourceConfig.webConfig = currentConfig.value;
          break;
        case 'wikipedia':
          sourceConfig.wikipediaConfig = currentConfig.value;
          break;
        case 'youtube':
          sourceConfig.youtubeConfig = currentConfig.value;
          break;
        case 's3':
        case 'gcs':
        case 'azure_blob':
          sourceConfig.cloudConfig = currentConfig.value;
          break;
        case 'onedrive':
        case 'sharepoint':
        case 'box':
        case 'google_drive':
          sourceConfig.enterpriseConfig = currentConfig.value;
          break;
      }

      emit('sources-configured', sourceConfig);
      emit('configure-processing');
    };

    // Clear state when data source changes
    watch(dataSource, () => {
      selectedFiles.value = [];
      currentConfig.value = {};
      isFormValid.value = false;
    });

    return {
      dataSourceOptions,
      dataSource,
      currentSourceComponent,
      currentSourceProps,
      isFormValid,
      handleConfigurationChange,
      handleValidationChange,
      configureProcessing,
    };
  },
});
</script>

<style scoped>
.cursor-pointer {
  cursor: pointer;
}

/* CSS hover styles removed - now handled by computed dropZoneStyle */

.drag-normal {
  background-color: #1976d2 !important;
}

/* Data source dropdown styling */
.data-source-select {
  max-width: 400px;
}

/* Ultra-specific Vuetify 3 selectors to force compact spacing */
.data-source-select :deep(.v-overlay__content .v-list) {
  padding: 2px 0 !important;
}

.data-source-select :deep(.v-overlay__content .v-list .v-list-item) {
  min-height: 28px !important;
  max-height: 28px !important;
  height: 28px !important;
  padding: 2px 16px !important;
  margin: 0 !important;
  font-size: 13px !important;
  line-height: 24px !important;
}

.data-source-select :deep(.v-overlay__content .v-list .v-list-item .v-list-item__content) {
  padding: 0 !important;
  margin: 0 !important;
  min-height: 28px !important;
  height: 28px !important;
}

.data-source-select :deep(.v-overlay__content .v-list .v-list-item .v-list-item-title) {
  font-size: 13px !important;
  line-height: 24px !important;
  padding: 0 !important;
  margin: 0 !important;
}

/* Target the actual rendered elements with highest specificity */
.data-source-select :deep(.v-overlay__content .v-list .v-list-item--disabled) {
  min-height: 28px !important;
  max-height: 28px !important;
  height: 28px !important;
  padding: 2px 16px !important;
  margin: 0 !important;
  opacity: 0.6 !important;
  font-size: 13px !important;
  line-height: 24px !important;
}

/* Force override any default Vuetify spacing */
.data-source-select :deep(.v-overlay__content .v-list .v-list-item__overlay) {
  display: none !important;
}

.data-source-select :deep(.v-overlay__content .v-list .v-list-item__underlay) {
  display: none !important;
}

/* Global override for this specific dropdown menu */
:global(.v-overlay .v-menu .v-list .v-list-item) {
  min-height: 28px !important;
  max-height: 28px !important;
  height: 28px !important;
  padding: 2px 16px !important;
  margin: 0 !important;
  font-size: 13px !important;
  line-height: 24px !important;
}
</style>
