// flexible-graphrag-ui/frontend-angular/src/app/components/sources/alfresco-source-form.component.ts
import { Component, Input, Output, EventEmitter, OnInit } from '@angular/core';
import { environment } from '../../../environments/environment';

export interface AlfrescoOAuth2Config {
  client_id?: string;
  client_secret?: string;
  token_endpoint?: string;
  scope?: string;
  access_token?: string;
  refresh_token?: string;
}

export interface AlfrescoSourceConfig {
  url: string;
  auth_method: string;
  username?: string;
  password?: string;
  oauth2?: AlfrescoOAuth2Config;
  path?: string;
}

@Component({
  selector: 'app-alfresco-source-form',
  template: `
    <app-base-source-form
      title="Alfresco Repository"
      description="Connect to an Alfresco content management system">

      <mat-form-field appearance="outline" class="full-width">
        <mat-label>Alfresco Base URL *</mat-label>
        <input matInput [(ngModel)]="url" (ngModelChange)="update()"
               [placeholder]="'e.g., ' + defaultUrl" required />
      </mat-form-field>

      <mat-form-field appearance="outline" class="full-width">
        <mat-label>Authentication</mat-label>
        <mat-select [(ngModel)]="authMethod" (ngModelChange)="update()">
          <mat-option value="basic">Basic (username / password)</mat-option>
          <mat-option value="ticket">Ticket (login ticket)</mat-option>
          <mat-option value="oauth2">OAuth2 (Bearer, via Identity Service)</mat-option>
        </mat-select>
      </mat-form-field>

      <div class="form-row" *ngIf="authMethod === 'basic' || authMethod === 'ticket'">
        <mat-form-field appearance="outline" class="half-width">
          <mat-label>Username *</mat-label>
          <input matInput [(ngModel)]="username" (ngModelChange)="update()" required />
        </mat-form-field>
        <mat-form-field appearance="outline" class="half-width">
          <mat-label>Password *</mat-label>
          <input matInput type="password" [(ngModel)]="password" (ngModelChange)="update()" required />
        </mat-form-field>
      </div>

      <ng-container *ngIf="authMethod === 'oauth2'">
        <div class="form-row">
          <mat-form-field appearance="outline" class="half-width">
            <mat-label>Client ID *</mat-label>
            <input matInput [(ngModel)]="clientId" (ngModelChange)="update()" required />
          </mat-form-field>
          <mat-form-field appearance="outline" class="half-width">
            <mat-label>Client Secret</mat-label>
            <input matInput type="password" [(ngModel)]="clientSecret" (ngModelChange)="update()" />
          </mat-form-field>
        </div>
        <mat-form-field appearance="outline" class="full-width">
          <mat-label>Token Endpoint</mat-label>
          <input matInput [(ngModel)]="tokenEndpoint" (ngModelChange)="update()"
                 placeholder="e.g., https://<keycloak>/realms/alfresco/protocol/openid-connect/token" />
        </mat-form-field>
        <mat-form-field appearance="outline" class="full-width">
          <mat-label>Scope (optional)</mat-label>
          <input matInput [(ngModel)]="scope" (ngModelChange)="update()" />
        </mat-form-field>
        <div class="form-row">
          <mat-form-field appearance="outline" class="half-width">
            <mat-label>Access Token (optional)</mat-label>
            <input matInput type="password" [(ngModel)]="accessToken" (ngModelChange)="update()" />
            <mat-hint>Provide a pre-obtained token instead of client_credentials</mat-hint>
          </mat-form-field>
          <mat-form-field appearance="outline" class="half-width">
            <mat-label>Refresh Token (optional)</mat-label>
            <input matInput type="password" [(ngModel)]="refreshToken" (ngModelChange)="update()" />
          </mat-form-field>
        </div>
      </ng-container>

      <mat-form-field appearance="outline" class="full-width">
        <mat-label>Path *</mat-label>
        <input matInput [(ngModel)]="path" (ngModelChange)="update()"
               placeholder="e.g., /Shared/GraphRAG" required />
      </mat-form-field>
    </app-base-source-form>
  `,
  styles: [`
    .full-width { width: 100%; margin-bottom: 16px; }
    .form-row { display: flex; gap: 16px; margin-bottom: 16px; }
    .half-width { flex: 1; }
  `],
  standalone: false
})
export class AlfrescoSourceFormComponent implements OnInit {
  defaultUrl = environment.alfrescoBaseUrl || 'http://localhost:8080';

  url: string = this.defaultUrl;
  authMethod: string = 'basic';
  path: string = '/Shared/GraphRAG';

  username: string = 'admin';
  password: string = 'admin';

  clientId: string = '';
  clientSecret: string = '';
  tokenEndpoint: string = '';
  scope: string = '';
  accessToken: string = '';
  refreshToken: string = '';

  @Input() value: any = null;
  @Output() valueChange = new EventEmitter<any>();
  @Output() configurationChange = new EventEmitter<AlfrescoSourceConfig>();
  @Output() validationChange = new EventEmitter<boolean>();

  ngOnInit() {
    const v = this.value || {};
    if (v.url !== undefined) this.url = v.url;
    if (v.auth_method) this.authMethod = v.auth_method;
    if (v.path !== undefined) this.path = v.path;
    if (v.username !== undefined) this.username = v.username;
    if (v.password !== undefined) this.password = v.password;
    const o = v.oauth2 || {};
    if (o.client_id !== undefined) this.clientId = o.client_id;
    if (o.client_secret !== undefined) this.clientSecret = o.client_secret;
    if (o.token_endpoint !== undefined) this.tokenEndpoint = o.token_endpoint;
    if (o.scope !== undefined) this.scope = o.scope;
    if (o.access_token !== undefined) this.accessToken = o.access_token;
    if (o.refresh_token !== undefined) this.refreshToken = o.refresh_token;
    this.update();
  }

  private isValid(): boolean {
    if (this.url.trim() === '' || this.path.trim() === '') return false;
    if (this.authMethod === 'oauth2') {
      return this.clientId.trim() !== '' && (this.accessToken.trim() !== '' || this.clientSecret.trim() !== '');
    }
    return this.username.trim() !== '' && this.password.trim() !== '';
  }

  private buildConfig(): AlfrescoSourceConfig {
    const config: AlfrescoSourceConfig = { url: this.url, auth_method: this.authMethod, path: this.path };
    if (this.authMethod === 'oauth2') {
      config.oauth2 = {
        client_id: this.clientId,
        client_secret: this.clientSecret || undefined,
        token_endpoint: this.tokenEndpoint || undefined,
        scope: this.scope || undefined,
        access_token: this.accessToken || undefined,
        refresh_token: this.refreshToken || undefined,
      };
    } else {
      config.username = this.username;
      config.password = this.password;
    }
    return config;
  }

  update(): void {
    const config = this.buildConfig();
    this.validationChange.emit(this.isValid());
    this.configurationChange.emit(config);
    this.valueChange.emit(config);
  }
}

// flexible-graphrag-ui/frontend-vue/src/components/sources/AlfrescoSourceForm.vue
<template>
  <BaseSourceForm
    title="Alfresco Repository"
    description="Connect to an Alfresco content management system"
  >
    <v-text-field
      :model-value="url"
      @update:model-value="(v: string) => url = v"
      label="Alfresco Base URL *"
      variant="outlined"
      class="mb-4"
      :placeholder="`e.g., ${defaultUrl}`"
      required
    />

    <v-select
      :model-value="authMethod"
      @update:model-value="(v: string) => authMethod = v"
      :items="authMethods"
      label="Authentication"
      variant="outlined"
      class="mb-4"
      density="compact"
    />

    <v-row v-if="authMethod === 'basic' || authMethod === 'ticket'" class="mb-4">
      <v-col cols="6">
        <v-text-field
          :model-value="username"
          @update:model-value="(v: string) => username = v"
          label="Username *"
          variant="outlined"
          required
        />
      </v-col>
      <v-col cols="6">
        <v-text-field
          :model-value="password"
          @update:model-value="(v: string) => password = v"
          label="Password *"
          type="password"
          variant="outlined"
          required
        />
      </v-col>
    </v-row>

    <template v-if="authMethod === 'oauth2'">
      <v-row class="mb-4">
        <v-col cols="6">
          <v-text-field
            :model-value="clientId"
            @update:model-value="(v: string) => clientId = v"
            label="Client ID *"
            variant="outlined"
            required
          />
        </v-col>
        <v-col cols="6">
          <v-text-field
            :model-value="clientSecret"
            @update:model-value="(v: string) => clientSecret = v"
            label="Client Secret"
            type="password"
            variant="outlined"
          />
        </v-col>
      </v-row>
      <v-text-field
        :model-value="tokenEndpoint"
        @update:model-value="(v: string) => tokenEndpoint = v"
        label="Token Endpoint"
        variant="outlined"
        class="mb-4"
        placeholder="e.g., https://<keycloak>/realms/alfresco/protocol/openid-connect/token"
      />
      <v-text-field
        :model-value="scope"
        @update:model-value="(v: string) => scope = v"
        label="Scope (optional)"
        variant="outlined"
        class="mb-4"
      />
      <v-row class="mb-4">
        <v-col cols="6">
          <v-text-field
            :model-value="accessToken"
            @update:model-value="(v: string) => accessToken = v"
            label="Access Token (optional)"
            type="password"
            variant="outlined"
            hint="Provide a pre-obtained token instead of client_credentials"
            persistent-hint
          />
        </v-col>
        <v-col cols="6">
          <v-text-field
            :model-value="refreshToken"
            @update:model-value="(v: string) => refreshToken = v"
            label="Refresh Token (optional)"
            type="password"
            variant="outlined"
          />
        </v-col>
      </v-row>
    </template>

    <v-text-field
      :model-value="path"
      @update:model-value="(v: string) => path = v"
      label="Path *"
      variant="outlined"
      class="mb-4"
      placeholder="e.g., /Shared/GraphRAG"
      required
    />
  </BaseSourceForm>
</template>

<script lang="ts">
import { defineComponent, ref, computed, watch } from 'vue';
import BaseSourceForm from './BaseSourceForm.vue';

export default defineComponent({
  name: 'AlfrescoSourceForm',
  components: {
    BaseSourceForm
  },
  props: {
    // Single-object persistence (see NuxeoSourceForm): seeds on mount, emits update:value on edit.
    value: { type: Object, default: null },
  },
  emits: ['configuration-change', 'validation-change', 'update:value'],
  setup(props, { emit }) {
    const v: any = props.value || {};
    const defaultUrl = import.meta.env.VITE_ALFRESCO_BASE_URL || 'http://localhost:8080';
    const defaultPath = import.meta.env.VITE_PROCESS_FOLDER_PATH || '/Shared/GraphRAG';

    const url = ref(v.url ?? defaultUrl);
    const authMethod = ref(v.auth_method ?? 'basic');
    const path = ref(v.path ?? defaultPath);

    const username = ref(v.username ?? 'admin');
    const password = ref(v.password ?? 'admin');

    const clientId = ref(v.oauth2?.client_id ?? '');
    const clientSecret = ref(v.oauth2?.client_secret ?? '');
    const tokenEndpoint = ref(v.oauth2?.token_endpoint ?? '');
    const scope = ref(v.oauth2?.scope ?? '');
    const accessToken = ref(v.oauth2?.access_token ?? '');
    const refreshToken = ref(v.oauth2?.refresh_token ?? '');

    const authMethods = [
      { title: 'Basic (username / password)', value: 'basic' },
      { title: 'Ticket (login ticket)', value: 'ticket' },
      { title: 'OAuth2 (Bearer, via Identity Service)', value: 'oauth2' },
    ];

    const isValid = computed(() => {
      if (url.value.trim() === '' || path.value.trim() === '') return false;
      if (authMethod.value === 'oauth2') {
        return clientId.value.trim() !== '' && (accessToken.value.trim() !== '' || clientSecret.value.trim() !== '');
      }
      return username.value.trim() !== '' && password.value.trim() !== '';
    });

    const config = computed(() => {
      const base: any = { url: url.value, auth_method: authMethod.value, path: path.value };
      if (authMethod.value === 'oauth2') {
        base.oauth2 = {
          client_id: clientId.value,
          client_secret: clientSecret.value || undefined,
          token_endpoint: tokenEndpoint.value || undefined,
          scope: scope.value || undefined,
          access_token: accessToken.value || undefined,
          refresh_token: refreshToken.value || undefined,
        };
      } else {
        base.username = username.value;
        base.password = password.value;
      }
      return base;
    });

    watch([isValid, config], ([newIsValid, newConfig]) => {
      emit('validation-change', newIsValid);
      emit('configuration-change', newConfig);
      emit('update:value', newConfig);  // persist live config to App
    }, { immediate: true, deep: true });

    return {
      defaultUrl,
      url,
      authMethod,
      authMethods,
      path,
      username,
      password,
      clientId,
      clientSecret,
      tokenEndpoint,
      scope,
      accessToken,
      refreshToken,
    };
  },
});
</script>
