// flexible-graphrag-ui/frontend-react/src/components/sources/NuxeoSourceForm.tsx
import React, { useEffect, useMemo, useState } from 'react';
import { TextField, Box, FormControl, InputLabel, Select, MenuItem } from '@mui/material';
import { BaseSourceForm, BaseSourceFormProps } from './BaseSourceForm';

type AuthMethod = 'basic' | 'oauth2' | 'token';

interface NuxeoSourceFormProps extends BaseSourceFormProps {
  // Single-object persistence: seeds the form on mount and receives the full config on every
  // edit, so App can hold one object and the form's state survives Sources<->Processing tab
  // switches (the Sources TabPanel unmounts on switch).
  value?: any;
  onChange?: (config: any) => void;
}

// Self-contained form: manages its own state and emits a complete Nuxeo config
// object via onConfigurationChange (matching the backend NuxeoConfig model).
export const NuxeoSourceForm: React.FC<NuxeoSourceFormProps> = ({
  value,
  onChange,
  onConfigurationChange,
  onValidationChange,
}) => {
  const defaultUrl = useMemo(
    () => import.meta.env.VITE_NUXEO_BASE_URL || 'http://localhost:8081/nuxeo',
    []
  );

  const [url, setUrl] = useState<string>(value?.url ?? defaultUrl);
  const [authMethod, setAuthMethod] = useState<AuthMethod>(value?.auth_method ?? 'basic');
  const [path, setPath] = useState<string>(value?.path ?? '/default-domain/workspaces');

  // Basic auth
  const [username, setUsername] = useState<string>(value?.username ?? 'Administrator');
  const [password, setPassword] = useState<string>(value?.password ?? 'Administrator');

  // OAuth2
  const [clientId, setClientId] = useState<string>(value?.oauth2?.client_id ?? '');
  const [clientSecret, setClientSecret] = useState<string>(value?.oauth2?.client_secret ?? '');
  const [accessToken, setAccessToken] = useState<string>(value?.oauth2?.access_token ?? '');
  const [refreshToken, setRefreshToken] = useState<string>(value?.oauth2?.refresh_token ?? '');
  const [tokenEndpoint, setTokenEndpoint] = useState<string>(value?.oauth2?.token_endpoint ?? '');

  const isValid = useMemo(() => {
    if (url.trim() === '') return false;
    // basic and token both authenticate with username/password (token mode fetches a
    // Nuxeo auth token from them on the backend, like Alfresco ticket).
    if (authMethod === 'basic' || authMethod === 'token') {
      return username.trim() !== '' && password.trim() !== '';
    }
    // oauth2
    return clientId.trim() !== '' && (accessToken.trim() !== '' || clientSecret.trim() !== '');
  }, [url, authMethod, username, password, clientId, clientSecret, accessToken]);

  const config = useMemo(() => {
    const base: any = { url, auth_method: authMethod, path };
    // token mode sends username/password; the backend fetches the auth token from them.
    if (authMethod === 'basic' || authMethod === 'token') {
      base.username = username;
      base.password = password;
    } else {
      base.oauth2 = {
        client_id: clientId,
        client_secret: clientSecret || undefined,
        access_token: accessToken || undefined,
        refresh_token: refreshToken || undefined,
        token_endpoint: tokenEndpoint || undefined,
      };
    }
    return base;
  }, [url, authMethod, path, username, password, clientId, clientSecret, accessToken, refreshToken, tokenEndpoint]);

  useEffect(() => {
    onValidationChange(isValid);
    onConfigurationChange(config);
    onChange?.(config);  // persist live config to App so it survives tab switches
  }, [isValid, config, onValidationChange, onConfigurationChange, onChange]);

  return (
    <BaseSourceForm
      title="Nuxeo Repository"
      description="Connect to a Nuxeo content management system"
    >
      <TextField
        fullWidth
        label="Nuxeo Base URL"
        variant="outlined"
        value={url}
        onChange={(e) => setUrl(e.target.value)}
        size="small"
        sx={{ mb: 2 }}
        placeholder="e.g., http://localhost:8081/nuxeo"
        helperText="Base repository URL (no /api/v1 suffix)"
      />

      <FormControl fullWidth size="small" sx={{ mb: 2 }}>
        <InputLabel>Authentication</InputLabel>
        <Select
          value={authMethod}
          label="Authentication"
          onChange={(e) => setAuthMethod(e.target.value as AuthMethod)}
        >
          <MenuItem value="basic">Basic (username / password)</MenuItem>
          <MenuItem value="oauth2">OAuth2 (Bearer)</MenuItem>
          <MenuItem value="token">Token (X-Authentication-Token)</MenuItem>
        </Select>
      </FormControl>

      {(authMethod === 'basic' || authMethod === 'token') && (
        <Box sx={{ display: 'flex', gap: 2, mb: 2 }}>
          <TextField
            fullWidth
            label="Username"
            variant="outlined"
            value={username}
            onChange={(e) => setUsername(e.target.value)}
            size="small"
          />
          <TextField
            fullWidth
            label="Password"
            type="password"
            variant="outlined"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            size="small"
          />
        </Box>
      )}

      {authMethod === 'oauth2' && (
        <Box sx={{ mb: 2 }}>
          <Box sx={{ display: 'flex', gap: 2, mb: 2 }}>
            <TextField
              fullWidth
              label="Client ID"
              variant="outlined"
              value={clientId}
              onChange={(e) => setClientId(e.target.value)}
              size="small"
            />
            <TextField
              fullWidth
              label="Client Secret"
              type="password"
              variant="outlined"
              value={clientSecret}
              onChange={(e) => setClientSecret(e.target.value)}
              size="small"
            />
          </Box>
          <Box sx={{ display: 'flex', gap: 2, mb: 2 }}>
            <TextField
              fullWidth
              label="Access Token"
              type="password"
              variant="outlined"
              value={accessToken}
              onChange={(e) => setAccessToken(e.target.value)}
              size="small"
              helperText="Obtain out-of-band (authorization code + PKCE)"
            />
            <TextField
              fullWidth
              label="Refresh Token"
              type="password"
              variant="outlined"
              value={refreshToken}
              onChange={(e) => setRefreshToken(e.target.value)}
              size="small"
            />
          </Box>
          <TextField
            fullWidth
            label="Token Endpoint (optional)"
            variant="outlined"
            value={tokenEndpoint}
            onChange={(e) => setTokenEndpoint(e.target.value)}
            size="small"
            placeholder="defaults to <url>/oauth2/token"
          />
        </Box>
      )}

      <TextField
        fullWidth
        label="Path"
        variant="outlined"
        value={path}
        onChange={(e) => setPath(e.target.value)}
        size="small"
        sx={{ mb: 2 }}
        placeholder="e.g., /default-domain/workspaces/GraphRAG"
      />
    </BaseSourceForm>
  );
};

// flexible-graphrag-ui/frontend-vue/src/components/sources/NuxeoSourceForm.vue
<template>
  <BaseSourceForm
    title="Nuxeo Repository"
    description="Connect to a Nuxeo content management system"
  >
    <v-text-field
      :model-value="url"
      @update:model-value="(v: string) => url = v"
      label="Nuxeo Base URL *"
      variant="outlined"
      class="mb-4"
      placeholder="e.g., http://localhost:8081/nuxeo"
      hint="Base repository URL (no /api/v1 suffix)"
      persistent-hint
      required
    />

    <v-select
      :model-value="authMethod"
      @update:model-value="(v: string) => authMethod = v"
      :items="authMethods"
      label="Authentication"
      variant="outlined"
      class="mb-4"
      density="compact"
    />

    <v-row v-if="authMethod === 'basic' || authMethod === 'token'" class="mb-4">
      <v-col cols="6">
        <v-text-field
          :model-value="username"
          @update:model-value="(v: string) => username = v"
          label="Username *"
          variant="outlined"
          required
        />
      </v-col>
      <v-col cols="6">
        <v-text-field
          :model-value="password"
          @update:model-value="(v: string) => password = v"
          label="Password *"
          type="password"
          variant="outlined"
          required
        />
      </v-col>
    </v-row>

    <template v-if="authMethod === 'oauth2'">
      <v-row class="mb-4">
        <v-col cols="6">
          <v-text-field
            :model-value="clientId"
            @update:model-value="(v: string) => clientId = v"
            label="Client ID *"
            variant="outlined"
            required
          />
        </v-col>
        <v-col cols="6">
          <v-text-field
            :model-value="clientSecret"
            @update:model-value="(v: string) => clientSecret = v"
            label="Client Secret"
            type="password"
            variant="outlined"
          />
        </v-col>
      </v-row>
      <v-row class="mb-4">
        <v-col cols="6">
          <v-text-field
            :model-value="accessToken"
            @update:model-value="(v: string) => accessToken = v"
            label="Access Token"
            type="password"
            variant="outlined"
            hint="Obtain out-of-band (authorization code + PKCE)"
            persistent-hint
          />
        </v-col>
        <v-col cols="6">
          <v-text-field
            :model-value="refreshToken"
            @update:model-value="(v: string) => refreshToken = v"
            label="Refresh Token"
            type="password"
            variant="outlined"
          />
        </v-col>
      </v-row>
      <v-text-field
        :model-value="tokenEndpoint"
        @update:model-value="(v: string) => tokenEndpoint = v"
        label="Token Endpoint (optional)"
        variant="outlined"
        class="mb-4"
        placeholder="defaults to <url>/oauth2/token"
      />
    </template>

    <v-text-field
      :model-value="path"
      @update:model-value="(v: string) => path = v"
      label="Path *"
      variant="outlined"
      class="mb-4"
      placeholder="e.g., /default-domain/workspaces/GraphRAG"
      hint="Path to the folder or document to process"
      persistent-hint
      required
    />
  </BaseSourceForm>
</template>

<script lang="ts">
import { defineComponent, ref, computed, watch } from 'vue';
import BaseSourceForm from './BaseSourceForm.vue';

export default defineComponent({
  name: 'NuxeoSourceForm',
  components: {
    BaseSourceForm
  },
  props: {
    // Single-object persistence: seeds the form on mount, emits update:value on every edit,
    // so App holds one object and state survives Sources<->Processing tab switches.
    value: { type: Object, default: null },
  },
  emits: ['configuration-change', 'validation-change', 'update:value'],
  setup(props, { emit }) {
    const v: any = props.value || {};
    const url = ref(v.url ?? (import.meta.env.VITE_NUXEO_BASE_URL || 'http://localhost:8081/nuxeo'));
    const authMethod = ref(v.auth_method ?? 'basic');
    const path = ref(v.path ?? '/default-domain/workspaces');

    const username = ref(v.username ?? 'Administrator');
    const password = ref(v.password ?? 'Administrator');

    const clientId = ref(v.oauth2?.client_id ?? '');
    const clientSecret = ref(v.oauth2?.client_secret ?? '');
    const accessToken = ref(v.oauth2?.access_token ?? '');
    const refreshToken = ref(v.oauth2?.refresh_token ?? '');
    const tokenEndpoint = ref(v.oauth2?.token_endpoint ?? '');

    const authMethods = [
      { title: 'Basic (username / password)', value: 'basic' },
      { title: 'OAuth2 (Bearer)', value: 'oauth2' },
      { title: 'Token (X-Authentication-Token)', value: 'token' },
    ];

    const isValid = computed(() => {
      if (url.value.trim() === '') return false;
      // basic and token both use username/password (token mode fetches the auth token
      // from them on the backend, like Alfresco ticket).
      if (authMethod.value === 'basic' || authMethod.value === 'token') {
        return username.value.trim() !== '' && password.value.trim() !== '';
      }
      return clientId.value.trim() !== '' && (accessToken.value.trim() !== '' || clientSecret.value.trim() !== '');
    });

    const config = computed(() => {
      const base: any = { url: url.value, auth_method: authMethod.value, path: path.value };
      // token mode sends username/password; the backend fetches the auth token from them.
      if (authMethod.value === 'basic' || authMethod.value === 'token') {
        base.username = username.value;
        base.password = password.value;
      } else {
        base.oauth2 = {
          client_id: clientId.value,
          client_secret: clientSecret.value || undefined,
          access_token: accessToken.value || undefined,
          refresh_token: refreshToken.value || undefined,
          token_endpoint: tokenEndpoint.value || undefined,
        };
      }
      return base;
    });

    watch([isValid, config], ([newIsValid, newConfig]) => {
      emit('validation-change', newIsValid);
      emit('configuration-change', newConfig);
      emit('update:value', newConfig);  // persist live config to App
    }, { immediate: true, deep: true });

    return {
      url,
      authMethod,
      authMethods,
      path,
      username,
      password,
      clientId,
      clientSecret,
      accessToken,
      refreshToken,
      tokenEndpoint,
    };
  },
});
</script>
